### Hello world
POST https://api.anthropic.com/v1/messages
Content-Type: application/json
anthropic-version: 2023-06-01
x-api-key: {{CLAUDE_API_KEY}}

{
    "model": "claude-sonnet-4-20250514",
    "max_tokens": 1024,
    "messages": [
        {"role": "user", "content": "Hello, world"}
    ]
}

### Grammar
POST https://api.anthropic.com/v1/messages
Content-Type: application/json
anthropic-version: 2023-06-01
x-api-key: {{CLAUDE_API_KEY}}

{
    "model": "claude-sonnet-4-20250514",
    "max_tokens": 1024,
    "system": "Assistant is a language expert designed to help users with grammar and spelling. Improve every text the user sends. Respond in the language the text is written in. Respond with just the improved text, nothing more.",
    "messages": [
      {
        "role": "user",
        "content": "The moon is more bright then it was yesterdate."
      },
      {
        "role": "assistant",
        "content": "The moon is brighter than it was yesterday."
      },
      {
        "role": "user",
        "content": "Hun moeten onmidellijk doen wat ik zech."
      },
      {
        "role": "assistant",
        "content": "Ze moeten onmiddellijk doen wat ik zeg."
      },
      {
        "role": "user",
        "content": "Try to be consise in you answers and donot elaborate to much."
      }
    ]
}
