### List all available OpenAI models
GET https://api.openai.com/v1/models
Authorization: Bearer {{OPENAI_API_KEY}}

### Grammar 
POST https://api.openai.com/v1/responses
Content-Type: application/json
Authorization: Bearer {{OPENAI_API_KEY}}

{
  "model": "gpt-5-nano",
  "input": [
    {
      "content": "Assistant is a language expert designed to help users with grammar and spelling. Improve every text the user sends. Respond in the language the text is written in. Respond with just the improved text, nothing more.",
      "role": "system"
    },
    {
      "content": "The moon is more bright then it was yesterdate.",
      "role": "user"
    },
    {
      "content": "The moon is brighter than it was yesterday.",
      "role": "assistant"
    },
    {
      "content": "Hun moeten onmidellijk doen wat ik zech.",
      "role": "user"
    },
    {
      "content": "Ze moeten onmiddellijk doen wat ik zeg.",
      "role": "assistant"
    },
    {
      "content": "Try to be consise in you answers and donot elaborate to much.",
      "role": "user"
    }
  ]
}

